#SPDX-License-Identifier: MIT-0
---
# handlers file for docker_host
- name: update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: update yum cache
  ansible.builtin.dnf:
    update_cache: yes

- name: restart ssh
  ansible.builtin.systemd:
    name: sshd
    state: restarted
